// <auto-generated>Do not edit this file manually. Your changes will be lost.</auto-generated>
using GameData;
namespace GameEntry.DataGenerated.GameEntry.ScopeDataTemplate.GameDataUnit;
internal static class TemplateUnit
{
    private static global::GameCore.EntitySystem.Data.GameDataUnit Root(ReadOnlySpan<byte> id)
    {
        return new(new(id))
        {
            Name = "英雄模板",
        };
    }

    internal static void OnRegisterGameData()
    {
        IGameData.SetTemplate("$GameEntry.ScopeDataTemplate.GameDataUnit.TemplateUnit.Root", Root);
    }
}
