// <auto-generated>
// Version: 0.0.4
// Timestamp: 1765008399
// Do not edit this file manually. Your changes will be lost.
// </auto-generated>
using GameData;
namespace GameEntry.ScopeData
{
    public static class GameDataAI
    {
        public static readonly GameLink<global::GameCore.AISystem.Data.GameDataAIThinkTree, global::GameCore.AISystem.Data.GameDataAIThinkTree> MonsterAI = new("$GameEntry.ScopeData.GameDataAI.MonsterAI.Root"u8);
    }
    public static class GameDataPlayerSettings
    {
        public static readonly GameLink<global::GameCore.PlayerAndUsers.Data.GameDataPlayerSettings, global::GameCore.PlayerAndUsers.Data.GameDataPlayerSettings> PlayerSettings = new("$GameEntry.ScopeData.GameDataPlayerSettings.PlayerSettings.Root"u8);
    }
    public static class GameDataScene
    {
        public static readonly GameLink<global::GameCore.SceneSystem.Data.GameDataScene, global::GameCore.SceneSystem.Data.GameDataScene> new_scene = new("$GameEntry.ScopeData.GameDataScene.new_scene.Root"u8);
    }
    public static class GameDataTargetingIndicator
    {
        public static readonly GameLink<global::GameCore.TargetingSystem.Data.GameDataTargetingIndicator, global::GameCore.TargetingSystem.Data.GameDataTargetingIndicator> AreaIndicator = new("$GameEntry.ScopeData.GameDataTargetingIndicator.AreaIndicator.Root"u8);
        public static readonly GameLink<global::GameCore.TargetingSystem.Data.GameDataTargetingIndicator, global::GameCore.TargetingSystem.Data.GameDataTargetingIndicator> LineIndicator = new("$GameEntry.ScopeData.GameDataTargetingIndicator.LineIndicator.Root"u8);
    }
}

namespace GameEntry
{
    internal class ScopeDataLoader : IGameClass
    {
        public static void OnRegisterGameClass()
        {
            Game.OnGameDataInitialization += OnGameDataInitialization;
            DataGenerated.GameEntry.ScopeDataTemplate.GameDataCamera.TemplateCamera.OnRegisterGameData();
            DataGenerated.GameEntry.ScopeDataTemplate.GameDataScene.TemplateScene.OnRegisterGameData();
            DataGenerated.GameEntry.ScopeDataTemplate.GameDataUnit.TemplateUnit.OnRegisterGameData();
        }

        private static void OnGameDataInitialization()
        {
            DataGenerated.GameEntry.ScopeData.GameDataAI.MonsterAI.OnRegisterGameData();
            DataGenerated.GameEntry.ScopeData.GameDataPlayerSettings.PlayerSettings.OnRegisterGameData();
            DataGenerated.GameEntry.ScopeData.GameDataScene.new_scene.OnRegisterGameData();
            DataGenerated.GameEntry.ScopeData.GameDataTargetingIndicator.AreaIndicator.OnRegisterGameData();
            DataGenerated.GameEntry.ScopeData.GameDataTargetingIndicator.LineIndicator.OnRegisterGameData();
        }
    }
}
