// <auto-generated>Do not edit this file manually. Your changes will be lost.</auto-generated>
using GameData;
namespace GameEntry.DataGenerated.GameEntry.ScopeDataTemplate.GameDataScene;
internal static class TemplateScene
{
    private static global::GameCore.SceneSystem.Data.GameDataScene Root(ReadOnlySpan<byte> id)
    {
        return new(new(id))
        {
            // DefaultCamera = "",
            HostedSceneTag = "new_scene",
            Size = new()
            {
                X = 128f,
                Y = 128f,
            },
        };
    }

    internal static void OnRegisterGameData()
    {
        IGameData.SetTemplate("$GameEntry.ScopeDataTemplate.GameDataScene.TemplateScene.Root", Root);
    }
}
