// <auto-generated>Do not edit this file manually. Your changes will be lost.</auto-generated>
using GameData;
namespace GameEntry.DataGenerated.GameEntry.ScopeData.GameDataTargetingIndicator;
internal static class AreaIndicator
{
    private static void Actor_AOEActor()
    {
        var id = "$GameEntry.ScopeData.GameDataTargetingIndicator.AreaIndicator.Actor_AOEActor"u8;
        var instance = new global::GameCore.ActorSystem.Data.GameDataActorParticle(new(id))
        {
            AutoPlay = true,
            Particle = new GameLink<global::GameCore.ResourceType.Data.GameDataParticle, global::GameCore.ResourceType.Data.GameDataParticle>("$GameEntry.ScopeData.GameDataTargetingIndicator.AreaIndicator.Particle_AOEParticle"u8),
        };
    }

    private static void Actor_PreTargetingCircle()
    {
        var id = "$GameEntry.ScopeData.GameDataTargetingIndicator.AreaIndicator.Actor_PreTargetingCircle"u8;
        var instance = new global::GameCore.ActorSystem.Data.GameDataActorParticle(new(id))
        {
            AutoPlay = true,
            InheritRotation = false,
            Particle = new GameLink<global::GameCore.ResourceType.Data.GameDataParticle, global::GameCore.ResourceType.Data.GameDataParticle>("$GameEntry.ScopeData.GameDataTargetingIndicator.AreaIndicator.Particle_PreTargetingCircle"u8),
        };
    }

    private static void Actor_PreTargetingHighlight()
    {
        var id = "$GameEntry.ScopeData.GameDataTargetingIndicator.AreaIndicator.Actor_PreTargetingHighlight"u8;
        var instance = new global::GameCore.ActorSystem.Data.GameDataActorHighlight(new(id))
        {
            AutoReverse = true,
            Duration = global::System.TimeSpan.FromMilliseconds(150.0),
            From = new()
            {
                Value = new()
                {
                    A = 255,
                    B = 192,
                    G = 192,
                    R = 255,
                },
            },
            // RepeatBehavior = "Forever",
            To = new()
            {
                Value = new()
                {
                    A = 255,
                    B = 128,
                    G = 128,
                    R = 255,
                },
            },
        };
    }

    private static void Actor_RangeActor()
    {
        var id = "$GameEntry.ScopeData.GameDataTargetingIndicator.AreaIndicator.Actor_RangeActor"u8;
        var instance = new global::GameCore.ActorSystem.Data.GameDataActorParticle(new(id))
        {
            AutoPlay = true,
            Particle = new GameLink<global::GameCore.ResourceType.Data.GameDataParticle, global::GameCore.ResourceType.Data.GameDataParticle>("$GameEntry.ScopeData.GameDataTargetingIndicator.AreaIndicator.Particle_RangeParticle"u8),
        };
    }

    private static void Particle_AOEParticle()
    {
        var id = "$GameEntry.ScopeData.GameDataTargetingIndicator.AreaIndicator.Particle_AOEParticle"u8;
        var instance = new global::GameCore.ResourceType.Data.GameDataParticle(new(id))
        {
            Asset = "effect/effect_new/effect_zhishiqi/eff_zhishiqi/ps_jineng_1/particle.effect",
            Radius = 66f,
        };
    }

    private static void Particle_PreTargetingCircle()
    {
        var id = "$GameEntry.ScopeData.GameDataTargetingIndicator.AreaIndicator.Particle_PreTargetingCircle"u8;
        var instance = new global::GameCore.ResourceType.Data.GameDataParticle(new(id))
        {
            Asset = "effect/effect_new/effect_guanghuan/eff_boss_guanghuan/particle.effect",
            AssetLayerScale = 0.4f,
            Radius = 51f,
        };
    }

    private static void Particle_RangeParticle()
    {
        var id = "$GameEntry.ScopeData.GameDataTargetingIndicator.AreaIndicator.Particle_RangeParticle"u8;
        var instance = new global::GameCore.ResourceType.Data.GameDataParticle(new(id))
        {
            Asset = "effect/effect_new/effect_zhishiqi/eff_zhishiqi/ps_yuanxing_1/particle.effect",
            Radius = 70f,
        };
    }

    private static void Root()
    {
        var id = "$GameEntry.ScopeData.GameDataTargetingIndicator.AreaIndicator.Root"u8;
        var instance = new global::GameCore.TargetingSystem.Data.GameDataTargetingIndicator(new(id))
        {
            CursorActors = [new GameLink<global::GameCore.ActorSystem.Data.GameDataActor, global::GameCore.ActorSystem.Data.GameDataActorParticle>("$GameEntry.ScopeData.GameDataTargetingIndicator.AreaIndicator.Actor_AOEActor"u8), new GameLink<global::GameCore.ActorSystem.Data.GameDataActor, global::GameCore.ActorSystem.Data.GameDataActorParticle>("$GameEntry.ScopeData.GameDataTargetingIndicator.AreaIndicator.Actor_PreTargetingCircle"u8)],
            Flags = new()
            {
                DebugDraw = false,
            },
            Name = "区域指示器",
            PreTargetingHighlightActors = [new GameLink<global::GameCore.ActorSystem.Data.GameDataActor, global::GameCore.ActorSystem.Data.GameDataActorHighlight>("$GameEntry.ScopeData.GameDataTargetingIndicator.AreaIndicator.Actor_PreTargetingHighlight"u8)],
            RangeActors = [new GameLink<global::GameCore.ActorSystem.Data.GameDataActor, global::GameCore.ActorSystem.Data.GameDataActorParticle>("$GameEntry.ScopeData.GameDataTargetingIndicator.AreaIndicator.Actor_RangeActor"u8)],
        };
    }

    internal static void OnRegisterGameData()
    {
        Actor_AOEActor();
        Actor_PreTargetingCircle();
        Actor_PreTargetingHighlight();
        Actor_RangeActor();
        Particle_AOEParticle();
        Particle_PreTargetingCircle();
        Particle_RangeParticle();
        Root();
    }
}
