// <auto-generated>Do not edit this file manually. Your changes will be lost.</auto-generated>
using GameData;
namespace GameEntry.DataGenerated.GameEntry.ScopeData.GameDataTargetingIndicator;
internal static class LineIndicator
{
    private static void Actor_LineCenterActor()
    {
        var id = "$GameEntry.ScopeData.GameDataTargetingIndicator.LineIndicator.Actor_LineCenterActor"u8;
        var instance = new global::GameCore.ActorSystem.Data.GameDataActorParticle(new(id))
        {
            AutoPlay = true,
            Particle = new GameLink<global::GameCore.ResourceType.Data.GameDataParticle, global::GameCore.ResourceType.Data.GameDataParticle>("$GameEntry.ScopeData.GameDataTargetingIndicator.LineIndicator.Particle_LineCenterParticle"u8),
        };
    }

    private static void Actor_LineImpactActor()
    {
        var id = "$GameEntry.ScopeData.GameDataTargetingIndicator.LineIndicator.Actor_LineImpactActor"u8;
        var instance = new global::GameCore.ActorSystem.Data.GameDataActorParticle(new(id))
        {
            AutoPlay = true,
            Particle = new GameLink<global::GameCore.ResourceType.Data.GameDataParticle, global::GameCore.ResourceType.Data.GameDataParticle>("$GameEntry.ScopeData.GameDataTargetingIndicator.LineIndicator.Particle_LineImpactParticle"u8),
        };
    }

    private static void Actor_LineLaunchActor()
    {
        var id = "$GameEntry.ScopeData.GameDataTargetingIndicator.LineIndicator.Actor_LineLaunchActor"u8;
        var instance = new global::GameCore.ActorSystem.Data.GameDataActorParticle(new(id))
        {
            AutoPlay = true,
            Particle = new GameLink<global::GameCore.ResourceType.Data.GameDataParticle, global::GameCore.ResourceType.Data.GameDataParticle>("$GameEntry.ScopeData.GameDataTargetingIndicator.LineIndicator.Particle_LineLaunchParticle"u8),
        };
    }

    private static void Actor_LineSegment()
    {
        var id = "$GameEntry.ScopeData.GameDataTargetingIndicator.LineIndicator.Actor_LineSegment"u8;
        var instance = new global::GameCore.ActorSystem.Data.GameDataActorSegmentedRectangle(new(id))
        {
            CenterActor = new GameLink<global::GameCore.ActorSystem.Data.GameDataActor, global::GameCore.ActorSystem.Data.GameDataActorParticle>("$GameEntry.ScopeData.GameDataTargetingIndicator.LineIndicator.Actor_LineCenterActor"u8),
            HeightTest = global::GameCore.ActorSystem.Data.Enum.ActorSegmentedHeight.LaunchSiteGround,
            ImpactActor = new GameLink<global::GameCore.ActorSystem.Data.GameDataActor, global::GameCore.ActorSystem.Data.GameDataActorParticle>("$GameEntry.ScopeData.GameDataTargetingIndicator.LineIndicator.Actor_LineImpactActor"u8),
            LaunchActor = new GameLink<global::GameCore.ActorSystem.Data.GameDataActor, global::GameCore.ActorSystem.Data.GameDataActorParticle>("$GameEntry.ScopeData.GameDataTargetingIndicator.LineIndicator.Actor_LineLaunchActor"u8),
            SegmentedFlags = new()
            {
                DebugDraw = false,
            },
        };
    }

    private static void Actor_PreTargetingHighlight()
    {
        var id = "$GameEntry.ScopeData.GameDataTargetingIndicator.LineIndicator.Actor_PreTargetingHighlight"u8;
        var instance = new global::GameCore.ActorSystem.Data.GameDataActorHighlight(new(id))
        {
            AutoReverse = true,
            Duration = global::System.TimeSpan.FromMilliseconds(150.0),
            From = new()
            {
                Value = new()
                {
                    A = 255,
                    B = 192,
                    G = 192,
                    R = 255,
                },
            },
            // RepeatBehavior = "Forever",
            To = new()
            {
                Value = new()
                {
                    A = 255,
                    B = 128,
                    G = 128,
                    R = 255,
                },
            },
        };
    }

    private static void Actor_RangeActor()
    {
        var id = "$GameEntry.ScopeData.GameDataTargetingIndicator.LineIndicator.Actor_RangeActor"u8;
        var instance = new global::GameCore.ActorSystem.Data.GameDataActorParticle(new(id))
        {
            AutoPlay = true,
            Particle = new GameLink<global::GameCore.ResourceType.Data.GameDataParticle, global::GameCore.ResourceType.Data.GameDataParticle>("$GameEntry.ScopeData.GameDataTargetingIndicator.LineIndicator.Particle_RangeParticle"u8),
        };
    }

    private static void Particle_LineCenterParticle()
    {
        var id = "$GameEntry.ScopeData.GameDataTargetingIndicator.LineIndicator.Particle_LineCenterParticle"u8;
        var instance = new global::GameCore.ResourceType.Data.GameDataParticle(new(id))
        {
            Asset = "effect/effect_new/effect_zhishiqi/eff_juxing/ps_zhong_1/particle.effect",
            Volume = new()
            {
                X = 128f,
                Y = 64f,
                Z = 128f,
            },
        };
    }

    private static void Particle_LineImpactParticle()
    {
        var id = "$GameEntry.ScopeData.GameDataTargetingIndicator.LineIndicator.Particle_LineImpactParticle"u8;
        var instance = new global::GameCore.ResourceType.Data.GameDataParticle(new(id))
        {
            Asset = "effect/effect_new/effect_zhishiqi/eff_zhixianxing/ps_tou_1/particle.effect",
            Volume = new()
            {
                X = 128f,
                Y = 64f,
                Z = 128f,
            },
        };
    }

    private static void Particle_LineLaunchParticle()
    {
        var id = "$GameEntry.ScopeData.GameDataTargetingIndicator.LineIndicator.Particle_LineLaunchParticle"u8;
        var instance = new global::GameCore.ResourceType.Data.GameDataParticle(new(id))
        {
            Asset = "effect/effect_new/effect_zhishiqi/eff_juxing/ps_wei_1/particle.effect",
            Volume = new()
            {
                X = 128f,
                Y = 64f,
                Z = 128f,
            },
        };
    }

    private static void Particle_RangeParticle()
    {
        var id = "$GameEntry.ScopeData.GameDataTargetingIndicator.LineIndicator.Particle_RangeParticle"u8;
        var instance = new global::GameCore.ResourceType.Data.GameDataParticle(new(id))
        {
            Asset = "effect/effect_new/effect_zhishiqi/eff_zhishiqi/ps_yuanxing_1/particle.effect",
            Radius = 70f,
        };
    }

    private static void Root()
    {
        var id = "$GameEntry.ScopeData.GameDataTargetingIndicator.LineIndicator.Root"u8;
        var instance = new global::GameCore.TargetingSystem.Data.GameDataTargetingIndicator(new(id))
        {
            Flags = new()
            {
                DebugDraw = false,
            },
            Name = "直线指示器",
            PreTargetingHighlightActors = [new GameLink<global::GameCore.ActorSystem.Data.GameDataActor, global::GameCore.ActorSystem.Data.GameDataActorHighlight>("$GameEntry.ScopeData.GameDataTargetingIndicator.LineIndicator.Actor_PreTargetingHighlight"u8)],
            RangeActors = [new GameLink<global::GameCore.ActorSystem.Data.GameDataActor, global::GameCore.ActorSystem.Data.GameDataActorParticle>("$GameEntry.ScopeData.GameDataTargetingIndicator.LineIndicator.Actor_RangeActor"u8)],
            VectorLineActors = [new GameLink<global::GameCore.ActorSystem.Data.GameDataActor, global::GameCore.ActorSystem.Data.GameDataActorSegmentedRectangle>("$GameEntry.ScopeData.GameDataTargetingIndicator.LineIndicator.Actor_LineSegment"u8)],
        };
    }

    internal static void OnRegisterGameData()
    {
        Actor_LineCenterActor();
        Actor_LineImpactActor();
        Actor_LineLaunchActor();
        Actor_LineSegment();
        Actor_PreTargetingHighlight();
        Actor_RangeActor();
        Particle_LineCenterParticle();
        Particle_LineImpactParticle();
        Particle_LineLaunchParticle();
        Particle_RangeParticle();
        Root();
    }
}
