// <auto-generated>Do not edit this file manually. Your changes will be lost.</auto-generated>
using GameData;
namespace GameEntry.DataGenerated.GameEntry.ScopeData.GameDataAI;
internal static class MonsterAI
{
    private static void Root()
    {
        var id = "$GameEntry.ScopeData.GameDataAI.MonsterAI.Root"u8;
        var instance = new global::GameCore.AISystem.Data.GameDataAIThinkTree(new(id))
        {
            CombatBehaviorTree = new GameLink<global::GameCore.AISystem.Data.GameDataAINode, global::GameCore.AISystem.Data.GameDataAINodeSequence>("$GameEntry.ScopeData.GameDataAI.MonsterAI.SharedBehaviorTree_MonsterCombat"u8),
            Name = "怪物AI",
            ScanFilters = [
                new()
                {
                    Excluded = [global::GameCore.BaseType.UnitFilter.Item, global::GameCore.BaseType.UnitState.Invulnerable, global::GameCore.BaseType.UnitState.Dead],
                    Required = [global::GameCore.BaseType.UnitRelationship.Enemy, global::GameCore.BaseType.UnitFilter.Unit, global::GameCore.BaseType.UnitRelationship.Visible],
                }
            ],
            ScanSorts = [global::GameCore.BaseType.UnitFilter.Hero, global::GameCore.BaseType.UnitFilter.Unit],
        };
    }

    private static void SharedBehaviorTree_MonsterCombat()
    {
        var id = "$GameEntry.ScopeData.GameDataAI.MonsterAI.SharedBehaviorTree_MonsterCombat"u8;
        var instance = new global::GameCore.AISystem.Data.GameDataAINodeSequence(new(id))
        {
            Name = "怪物战斗行为树",
            Nodes = [new GameLink<global::GameCore.AISystem.Data.GameDataAINode, global::GameCore.AISystem.Data.GameDataAINodeValidateScan>("$GameEntry.ScopeData.GameDataAI.MonsterAI.SharedNode_ScanEnemies"u8), new GameLink<global::GameCore.AISystem.Data.GameDataAINode, global::GameCore.AISystem.Data.GameDataAINodeValidateCast>("$GameEntry.ScopeData.GameDataAI.MonsterAI.SharedNode_CastAtTarget"u8)],
        };
    }

    private static void SharedNode_CastAtTarget()
    {
        var id = "$GameEntry.ScopeData.GameDataAI.MonsterAI.SharedNode_CastAtTarget"u8;
        var instance = new global::GameCore.AISystem.Data.GameDataAINodeValidateCast(new(id))
        {
            DoRecast = true,
            Name = "怪物对目标施法",
        };
    }

    private static void SharedNode_ScanEnemies()
    {
        var id = "$GameEntry.ScopeData.GameDataAI.MonsterAI.SharedNode_ScanEnemies"u8;
        var instance = new global::GameCore.AISystem.Data.GameDataAINodeValidateScan(new(id))
        {
            IgnoreLeash = false,
            Name = "怪物扫描敌人",
        };
    }

    internal static void OnRegisterGameData()
    {
        Root();
        SharedBehaviorTree_MonsterCombat();
        SharedNode_CastAtTarget();
        SharedNode_ScanEnemies();
    }
}
