// <auto-generated>Do not edit this file manually. Your changes will be lost.</auto-generated>
using GameData;
namespace GameEntry.DataGenerated.GameEntry.ScopeData.GameDataScene;
internal static class new_scene
{
    private static void Camera_0()
    {
        var id = "$GameEntry.ScopeData.GameDataScene.new_scene.Camera_0"u8;
        var template = "$GameEntry.ScopeDataTemplate.GameDataCamera.TemplateCamera.Root";
        var instance = IGameData.Create<global::GameUI.CameraSystem.Data.GameDataCamera>(template, id);
        if (instance == null)
        {
            Game.Logger.LogWarning($"{template}不存在或不是global::GameUI.CameraSystem.Data.GameDataCamera类型");
            return;
        }
        instance.Name = "默认镜头";
        instance.PositionMode = global::GameCore.CameraSystem.Enum.CameraPositionMode.CameraLocation;
        var rotation1 = instance.Rotation;
        {
            rotation1.Pitch = -70f;
            rotation1.Roll = 0f;
            rotation1.Yaw = -90f;
        }
        instance.Rotation = rotation1;
        instance.RotationOrder = global::GameCore.CameraSystem.Enum.CameraRotationOrder.YawPitchRoll;
        instance.TargetingMode = global::GameCore.CameraSystem.Enum.CameraTargetingMode.Follow;
        instance.TargetX = 2314.7f;
        instance.TargetY = 2824.2f;
        instance.TargetZOffset = 1513.5f;
    }

    private static void Root()
    {
        var id = "$GameEntry.ScopeData.GameDataScene.new_scene.Root"u8;
        var instance = new global::GameCore.SceneSystem.Data.GameDataScene(new(id))
        {
            DefaultCamera = new GameLink<global::GameUI.CameraSystem.Data.GameDataCamera, global::GameUI.CameraSystem.Data.GameDataCamera>("$GameEntry.ScopeData.GameDataScene.new_scene.Camera_0"u8),
            HostedSceneTag = "new_scene",
            Name = "默认场景",
            Size = new()
            {
                X = 4096f,
                Y = 4096f,
            },
        };
    }

    internal static void OnRegisterGameData()
    {
        Camera_0();
        Root();
    }
}
