// <auto-generated>Do not edit this file manually. Your changes will be lost.</auto-generated>
using GameData;
namespace GameEntry.DataGenerated.GameEntry.ScopeDataTemplate.GameDataCamera;
internal static class TemplateCamera
{
    private static global::GameUI.CameraSystem.Data.GameDataCamera Root(ReadOnlySpan<byte> id)
    {
        return new(new(id))
        {
            DisplayDebugInfo = false,
            FarClipPlane = 100000f,
            FieldOfView = 45f,
            FieldOfViewFor2K = 25f,
            FocalLength = new()
            {
                Max = 1600f,
                Min = 1000f,
            },
            FollowMainUnitByDefault = false,
            FollowMoveRateRange = new()
            {
                Max = 4000f,
                Min = 2000f,
            },
            // FollowMoveTime = "${System.TimeSpan.Zero}",
            FreeTargetChangeThreshold = 15f,
            GestureMoveMaxSpeed = 5000f,
            GestureMoveMultiplier = 1f,
            GestureScaleMaxSpeed = 5000f,
            GestureScaleMultiplier = 1f,
            NearClipPlane = 1f,
            Orthographic = false,
            PositionBias = new()
            {
                X = 0f,
                Y = 0f,
                Z = 0f,
            },
            PositionMode = global::GameCore.CameraSystem.Enum.CameraPositionMode.FocalPoint,
            Rotation = new()
            {
                Pitch = -45f,
                Roll = 0f,
                Yaw = 0f,
            },
            RotationOrder = global::GameCore.CameraSystem.Enum.CameraRotationOrder.YawPitchRoll,
            SceneBounds = new()
            {
                Bottom = 0f,
                Left = 0f,
                Right = 0f,
                Top = 0f,
            },
            TargetingMode = global::GameCore.CameraSystem.Enum.CameraTargetingMode.Follow,
            TargetX = 0f,
            TargetY = 0f,
            TargetZOffset = 0f,
            UseSpringArm = false,
            ZoomFocalLengthRate = 750f,
            ZoomRotationRange = new()
            {
                Max = new()
                {
                    Pitch = -70f,
                    Roll = 0f,
                    Yaw = 0f,
                },
                Min = new()
                {
                    Pitch = -30f,
                    Roll = 0f,
                    Yaw = 0f,
                },
            },
            ZoomRotationRate = new()
            {
                Pitch = -70f,
                Roll = 0f,
                Yaw = 0f,
            },
            ZoomStageCount = 4,
        };
    }

    internal static void OnRegisterGameData()
    {
        IGameData.SetTemplate("$GameEntry.ScopeDataTemplate.GameDataCamera.TemplateCamera.Root", Root);
    }
}
