// <auto-generated>Do not edit this file manually. Your changes will be lost.</auto-generated>
using GameData;
namespace GameEntry.DataGenerated.GameEntry.ScopeData.GameDataPlayerSettings;
internal static class PlayerSettings
{
    private static void Root()
    {
        var id = "$GameEntry.ScopeData.GameDataPlayerSettings.PlayerSettings.Root"u8;
        var instance = new global::GameCore.PlayerAndUsers.Data.GameDataPlayerSettings(new(id))
        {
            PlayerTeamData = [
                new()
                {
                    DisplayName = "队伍 0",
                    Players = [
                        new()
                        {
                            Controller = global::EngineInterface.BaseType.ControllerType.Computer,
                            Id = 0,
                            IsNeutral = true,
                        }
                    ],
                },
                new()
                {
                    DisplayName = "队伍 1",
                    Players = [
                        new()
                        {
                            Controller = global::EngineInterface.BaseType.ControllerType.User,
                            Id = 1,
                        },
                        new()
                        {
                            Controller = global::EngineInterface.BaseType.ControllerType.Computer,
                            Id = 2,
                        }
                    ],
                },
                new()
                {
                    DisplayName = "队伍 2",
                    Players = [
                        new()
                        {
                            Controller = global::EngineInterface.BaseType.ControllerType.Computer,
                            Id = 3,
                        },
                        new()
                        {
                            Controller = global::EngineInterface.BaseType.ControllerType.Computer,
                            Id = 4,
                        }
                    ],
                }
            ],
        };
    }

    internal static void OnRegisterGameData()
    {
        Root();
    }
}
